-- ═══════════════════════════════════════════════════════════════════════════
-- FANCY RSVP — GRANT SUPER ADMIN
--
-- ── READ THIS FIRST: this platform does NOT use Supabase Auth ──
--
-- Organizer and admin accounts live in `public.organizations`, with the password
-- bcrypt-hashed into `organizations.password_hash` and the identity being a
-- SELF-ISSUED uuid in `organizations.owner_user_id` — generated by
-- crypto.randomUUID() in authController.register(), never by Supabase.
--
-- `auth.users` is unused by the login flow. Inserting a row there (and hashing a
-- password into it with crypt()) does nothing at all: the app never reads that
-- table, and the uuid it generates will NOT match organizations.owner_user_id.
--
-- Every RBAC lookup keys on organizations.owner_user_id:
--   services/rbacService.loadAccessContext(userId)
--     → organizations WHERE owner_user_id = userId
--     → admin_users    WHERE user_id      = userId   ← the SAME uuid
--        → admin_user_roles → roles.key = 'super_admin'
--
-- So granting admin against an auth.users id silently grants nothing.
--
-- ── PREREQUISITE ──
-- Register the account through the app's own sign-up page FIRST. That is what
-- creates the organizations row, the password, and the owner_user_id this script
-- needs. Then run this.
-- ═══════════════════════════════════════════════════════════════════════════

-- The email is repeated literally in each statement rather than held in a
-- variable: psql's \set does not exist in the Supabase SQL editor, and a silent
-- meta-command failure here would be worse than the repetition.

-- ─── 0. Refuse loudly if the account does not exist yet ────────────────────
DO $$
DECLARE v_email text := 'gooamr88@gmail.com';
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.organizations WHERE lower(email) = lower(v_email)) THEN
    RAISE EXCEPTION
      'No organizations row for %. Register through the app sign-up page first — this script grants admin to an EXISTING account, it cannot create one (the password must be hashed by the app).', v_email;
  END IF;
END $$;

-- ─── 1. Make sure the account can actually log in ──────────────────────────
-- Registration gates login on a verified email (a 6-digit OTP). On a freshly
-- cleaned database there is no inbox round-trip worth doing for your own admin
-- account, so confirm it here.
UPDATE public.organizations
   SET email_verified = true,
       registration_otp = NULL,
       registration_otp_expires_at = NULL,
       otp_attempts = 0,
       status = 'active'
 WHERE lower(email) = lower('gooamr88@gmail.com');

-- ─── 2. The super_admin role must exist ────────────────────────────────────
-- clean_database.sql reseeds this, but a partial clean (or a restore that
-- skipped the reseed) leaves `roles` empty — and then step 4's JOIN matches
-- nothing and inserts nothing, silently.
INSERT INTO public.roles (key, name, description, is_system)
VALUES ('super_admin', 'Super Admin',
        'Unrestricted platform owner. Implicitly holds every permission.', true)
ON CONFLICT (key) DO NOTHING;

-- ─── 3. Legacy flag ────────────────────────────────────────────────────────
INSERT INTO public.user_roles (user_id, role)
SELECT owner_user_id, 'super_admin'
  FROM public.organizations
 WHERE lower(email) = lower('gooamr88@gmail.com')
ON CONFLICT (user_id) DO UPDATE SET role = 'super_admin';

-- ─── 4. RBAC: the admin account ────────────────────────────────────────────
-- status MUST be 'active' — rbacService treats anything else as not an admin.
INSERT INTO public.admin_users (user_id, status, mfa_enabled)
SELECT owner_user_id, 'active', false
  FROM public.organizations
 WHERE lower(email) = lower('gooamr88@gmail.com')
ON CONFLICT (user_id) DO UPDATE SET status = 'active';

-- ─── 5. RBAC: the role grant ───────────────────────────────────────────────
INSERT INTO public.admin_user_roles (admin_user_id, role_id)
SELECT au.id, r.id
  FROM public.admin_users au
  JOIN public.organizations o ON o.owner_user_id = au.user_id
  JOIN public.roles r ON r.key = 'super_admin'
 WHERE lower(o.email) = lower('gooamr88@gmail.com')
ON CONFLICT (admin_user_id, role_id) DO NOTHING;

-- ─── 6. Verify — every column must be non-null ─────────────────────────────
-- This mirrors rbacService.loadAccessContext exactly. If `rbac_role` is NULL,
-- the button will NOT appear no matter what the other columns say.
SELECT
  o.email,
  o.owner_user_id                        AS app_user_id,
  o.email_verified,
  o.status                               AS org_status,
  (o.password_hash IS NOT NULL)          AS can_log_in,
  ur.role                                AS legacy_role,
  au.status                              AS admin_status,
  r.key                                  AS rbac_role,
  CASE
    WHEN r.key = 'super_admin' AND au.status = 'active'
      THEN 'OK — super admin resolves'
    WHEN au.id IS NULL
      THEN 'BROKEN — no admin_users row'
    WHEN r.key IS NULL
      THEN 'BROKEN — admin_users exists but no super_admin role is linked'
    ELSE 'BROKEN — admin_users row is not active'
  END                                    AS verdict
FROM public.organizations o
LEFT JOIN public.user_roles ur       ON ur.user_id = o.owner_user_id
LEFT JOIN public.admin_users au      ON au.user_id = o.owner_user_id
LEFT JOIN public.admin_user_roles aur ON aur.admin_user_id = au.id
LEFT JOIN public.roles r             ON r.id = aur.role_id
WHERE lower(o.email) = lower('gooamr88@gmail.com');

-- ── After running ──
-- rbacService caches the access context for 60 seconds, so wait a minute (or
-- restart the API) and hard-refresh the dashboard. A re-login is NOT required:
-- middleware/auth.js resolves isSuperAdmin live on every request rather than
-- reading it from the cookie.
--
-- OPTIONAL CLEANUP: the auth.users / auth.identities rows created by the older
-- script are inert but confusing. To remove them:
--   DELETE FROM auth.identities WHERE user_id IN (SELECT id FROM auth.users WHERE email = 'gooamr88@gmail.com');
--   DELETE FROM auth.users WHERE email = 'gooamr88@gmail.com';
