package com.fancyrsvp.checkin.util

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * CROSS-LANGUAGE CONTRACT TEST — the Kotlin half.
 *
 * The bundle content hash is computed independently by two implementations:
 *   • backend/services/checkinSyncService.js  → canonicalizeGuests()
 *   • android/.../util/BundleIntegrity.kt     → canonicalize()
 *
 * If they disagree by one byte, EVERY bundle download fails verification and no
 * device can ever be armed for an event — presenting as "preparation is broken"
 * with nothing pointing at a serialisation detail as the cause.
 *
 * The fixture and expected output below are duplicated VERBATIM from
 * backend/test/checkinBundleHashContract.test.js, and the expected values were
 * generated by running the real server implementation. Neither side may be
 * changed without the other; a one-sided edit fails here or there instead of
 * silently in the field.
 *
 * Runs on the JVM (no device or emulator needed):
 *   ./gradlew :app:testDebugUnitTest
 *
 * Two conventions in this file, both there because a single wrong byte breaks
 * every device at once:
 *   • control characters are built from code points, never written as raw bytes
 *     (a literal form feed in a .kt source is invisible in review and is
 *     silently rewritten by reformatting tools);
 *   • expected ESCAPE SEQUENCES are built with explicit concatenation, so
 *     "\\u0001" unambiguously means the six characters backslash-u-0-0-0-1 and
 *     not the control character itself.
 */
class BundleIntegrityTest {

    private val fixture = listOf(
        BundleIntegrity.HashableGuest("b-2", "p1", "Bob \"Bobby\" Smith", "Table 2", "standard"),
        BundleIntegrity.HashableGuest("a-1", "p1", "أحمد عبد الله", null, "vip"),
        BundleIntegrity.HashableGuest("c-3", "p2", "José Al-Masri", "Table 10", null),
        BundleIntegrity.HashableGuest("d-4", "p2", "Tab\tand\nNewline\\slash", "", "family"),
    )

    private val expectedCanonical =
        """[["a-1","p1","أحمد عبد الله","","vip"],""" +
            """["b-2","p1","Bob \"Bobby\" Smith","Table 2","standard"],""" +
            """["c-3","p2","José Al-Masri","Table 10","standard"],""" +
            """["d-4","p2","Tab\tand\nNewline\\slash","","family"]]"""

    private val expectedSha256 =
        "9908c85762112bd17249e4050e8f3579615cc7ee595dcccb4fd539e3ce63dc9a"

    /** Wraps a name in the single-guest canonical form, for the escaping tests. */
    private fun canonOf(name: String): String = BundleIntegrity.canonicalize(
        listOf(BundleIntegrity.HashableGuest("x", "p", name, null, null)),
    )

    @Test
    fun `CONTRACT canonical serialisation matches the server exactly`() {
        assertEquals(expectedCanonical, BundleIntegrity.canonicalize(fixture))
    }

    @Test
    fun `CONTRACT content hash matches the server exactly`() {
        assertEquals(expectedSha256, BundleIntegrity.contentHash(fixture))
    }

    @Test
    fun `CONTRACT input order cannot affect the hash`() {
        val shuffled = listOf(fixture[3], fixture[1], fixture[0], fixture[2])
        assertEquals(expectedCanonical, BundleIntegrity.canonicalize(shuffled))
    }

    @Test
    fun `CONTRACT a null category defaults to standard`() {
        assertTrue(
            BundleIntegrity.canonicalize(fixture)
                .contains(""""c-3","p2","José Al-Masri","Table 10","standard""""),
        )
    }

    @Test
    fun `CONTRACT a null table and an empty table both serialise as empty string`() {
        val canon = BundleIntegrity.canonicalize(fixture)
        assertTrue("null tableName", canon.contains(""""a-1","p1","أحمد عبد الله","","vip""""))
        assertTrue("empty tableName", canon.contains(""""Newline\\slash","","family""""))
    }

    @Test
    fun `CONTRACT Arabic is not escaped so the hash covers its UTF-8 bytes`() {
        val canon = BundleIntegrity.canonicalize(fixture)
        assertTrue(canon.contains("أحمد عبد الله"))
        assertFalse("no unicode escaping of Arabic", canon.contains("\\u06"))
    }

    @Test
    fun `CONTRACT no incidental whitespace`() {
        val canon = BundleIntegrity.canonicalize(fixture)
        assertFalse("no space after open bracket", canon.contains("[ "))
        assertFalse("no space after comma", canon.contains(", "))
        assertFalse("no literal newline", canon.contains("\n"))
        assertFalse("no literal tab", canon.contains("\t"))
    }

    @Test
    fun `an empty guest list hashes deterministically`() {
        assertEquals("[]", BundleIntegrity.canonicalize(emptyList()))
        assertEquals(
            "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
            BundleIntegrity.contentHash(emptyList()),
        )
    }

    // ── Escaping, matched against JSON.stringify's behaviour ──

    @Test
    fun `control characters use the short escape forms, matching JSON stringify`() {
        val name = buildString {
            append('a'); append(0x08.toChar())   // backspace
            append('b'); append(0x0C.toChar())   // form feed
            append('c')
        }
        val canon = canonOf(name)
        assertTrue("backspace short form", canon.contains("a" + "\\b" + "b"))
        assertTrue("form feed short form", canon.contains("b" + "\\f" + "c"))
    }

    @Test
    fun `an exotic control character falls back to a four-digit unicode escape`() {
        val name = buildString { append('a'); append(0x01.toChar()); append('b') }
        // "\\u0001" is the six characters backslash-u-0-0-0-1, NOT the control
        // character — which is exactly what the canonical form should contain.
        assertTrue(canonOf(name).contains("a" + "\\u0001" + "b"))
    }

    @Test
    fun `a quote and a backslash in a name are escaped, not dropped`() {
        assertTrue(canonOf("He said \"hi\"\\").contains("""He said \"hi\"\\"""))
    }

    @Test
    fun `a forward slash is NOT escaped, matching JSON stringify`() {
        // Some JSON encoders escape "/" as "\/". JSON.stringify does not, and if
        // this side did, every hash would diverge.
        assertTrue(canonOf("a/b").contains("a/b"))
    }

    // ── Verification behaviour ──

    @Test
    fun `a complete bundle verifies`() {
        assertEquals(
            BundleIntegrity.Verification.Valid,
            BundleIntegrity.verify(fixture, 4, expectedSha256),
        )
    }

    @Test
    fun `a truncated bundle is rejected on count, the most actionable failure`() {
        val result = BundleIntegrity.verify(fixture.take(3), 4, expectedSha256)
        assertTrue(result is BundleIntegrity.Verification.CountMismatch)
        result as BundleIntegrity.Verification.CountMismatch
        assertEquals(4, result.expected)
        assertEquals(3, result.actual)
    }

    @Test
    fun `a bundle with the right count but altered content is rejected on hash`() {
        // The exact failure a silent mid-flight corruption would produce: the
        // record count still matches, so only the hash catches it.
        val tampered = fixture.map {
            if (it.id == "b-2") it.copy(tableName = "Table 9") else it
        }
        assertTrue(
            BundleIntegrity.verify(tampered, 4, expectedSha256)
                is BundleIntegrity.Verification.HashMismatch,
        )
    }

    @Test
    fun `hash comparison is case-insensitive so hex casing cannot break a device`() {
        assertEquals(
            BundleIntegrity.Verification.Valid,
            BundleIntegrity.verify(fixture, 4, expectedSha256.uppercase()),
        )
    }

    @Test
    fun `dropping one guest changes the hash - this is what catches a truncated download`() {
        assertNotEquals(expectedSha256, BundleIntegrity.contentHash(fixture.take(3)))
    }
}
